uploads = []
generated = []

[[outputs]]
id = "4h9fwZV9M0kLuxn-9Jwce"
uri = "file://SAFEZONE.md"
type = "text"
title = "SafeZone Documentation"

[[outputs]]
id = "lhQKsIR5idC6i6IUXcvfV"
uri = "file://BIBLIOGRAPHY.md"
type = "text"
title = "SafeZone Bibliography"

[[outputs]]
id = "k_DinR6TctLIwq7Mf913b"
uri = "file://screenshots/safezone_homepage.jpg"
type = "image"
title = "SafeZone - Homepage & Search"

[[outputs]]
id = "km2H5E7LhxnqGkfr4WYdH"
uri = "file://screenshots/safezone_safety_tips.jpg"
type = "image"
title = "SafeZone - Safety Tips Section"

[[outputs]]
id = "94TGqgaKZVU_VcQ8eAvmb"
uri = "file://screenshots/safezone_faq.jpg"
type = "image"
title = "SafeZone - FAQ Section"

[[outputs]]
id = "TNMU7R6PANvjYP3jwaV73"
uri = "file://screenshots/safezone_version1.jpg"
type = "image"
title = "SafeZone - Version 1 (Original Design)"

[[outputs]]
id = "nwBGvnM16rPbZmT8FwmL_"
uri = "file://SOURCECODE.md"
type = "text"
title = "SafeZone - Complete Source Code"

[[outputs]]
id = "pu8eUBjhNhIo6GEYZMdNA"
uri = "file://SafeZone_Business_Canvas.pdf"
type = "pdf"
title = "SafeZone - Business Model Canvas (PDF)"
